/*\
title: $:/plugins/tobibeer/preview/link.js
type: application/javascript
module-type: startup

Enhances the link widget for on-hover previews

@preserve
\*/
(function(){var block,CoreLink=require("$:/core/modules/widgets/link.js").link,renderCore=CoreLink.prototype.render,clickCore=CoreLink.prototype.handleClickEvent;CoreLink.prototype.render=function(){renderCore.apply(this,arguments);var self=this,wiki=this.wiki,el=this.domNodes[0],to=wiki.getTiddler(self.to),defaults="$:/plugins/tobibeer/preview/defaults/",preview="$:/temp/tobibeer/preview-",keys=$tw.utils.parseKeyDescriptorTB(wiki.getTextReference(defaults+"keys","").toUpperCase()),delay=wiki.getTextReference(defaults+"delay").toUpperCase(),getInfo=function(el){var info=$tw.popup.popupInfo(el),level=info.popupLevel;return(wiki.getTextReference(preview+level)&&wiki.getTextReference(preview+level+"-tiddler")===self.to?null:info)},showPopup=function(){var level,info=getInfo(el);if(info){level=info.popupLevel;clearTimeout(self.previewTimeout);$tw.popup.cancel(level);level++;wiki.setText(preview+level+"-tiddler","text",null,self.to);if($tw.popup.findPopup(preview+level)===-1){setTimeout(function(){$tw.popup.triggerPopup({domNode:el,title:preview+level,wiki:wiki});block=0},50)}}},show=function(){var ex,exclude,doShow=1,not=wiki.getTextReference(defaults+"not","");if(not){$tw.utils.each(not.split(" "),function(n){var node=el;while(node&&doShow){if($tw.utils.hasClass(node,n)){doShow=0;return false}node=node.parentNode}})}if(doShow){exclude=wiki.getTextReference(defaults+"exclude","");ex=exclude?wiki.filterTiddlers(exclude):[];if(ex.indexOf(self.to)>=0){doShow=0}}return doShow};delay=delay!==undefined?parseInt(delay):null;if(delay!==null&&isNaN(delay)){delay=0}if(to){$tw.utils.addClass(el,"tc-popup-handle");$tw.utils.addClass(el,"tc-popup-absolute");el.addEventListener("mousedown",function(event){var ev=event||window.event;if(ev.button===1&&wiki.getTextReference("$:/plugins/tobibeer/preview/config/middleclickpreview","enable")==="enable"){ev.preventDefault();showPopup(self,el)}});["mouseover","mouseout"].forEach(function(e){el.addEventListener(e,function(event){var ev=event||window.event;if(e==="mouseover"){if(show()){if(!ev.keyCode){ev.keyCode=0}if($tw.utils.checkKeyDescriptorTB(ev,keys)){if(!block){block=1;showPopup()}}else if(delay!==null){block=0;self.previewTimeout=setTimeout(showPopup,delay)}}}else{block=0;clearTimeout(self.previewTimeout);if(!event.relatedTarget?.classList.contains("tc-preview-tiddler")){$tw.popup.cancel(Math.max(0,getInfo(el).popupLevel))}}})})}};CoreLink.prototype.handleClickEvent=function(){clickCore.apply(this,arguments);clearTimeout(this.previewTimeout);$tw.popup.cancel(Math.max(0,$tw.popup.popupInfo(this.domNodes[0]).popupLevel))}})();